# Generated by Django 4.1.3 on 2022-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksertificate',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
