# Generated by Django 4.1.3 on 2022-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_checksertificate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=200)),
                ('url', models.TextField(blank=True, null=True)),
                ('ism_familiya', models.CharField(max_length=200)),
                ('kurs_nomi', models.TextField()),
                ('kurs_soati', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckSertificate',
        ),
    ]
