# Generated by Django 4.1.3 on 2022-11-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sertificate_delete_checksertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='upload_link',
            field=models.TextField(default='media/pdf/'),
        ),
    ]
